FROM node:alpine

RUN mkdir -p /usr/src/trip-finder-backend && chown -R node:node /usr/src/trip-finder-backend

WORKDIR /usr/src/trip-finder-backend

COPY package.json yarn.lock ./

USER node

RUN yarn install --pure-lockfile

COPY --chown=node:node . .

EXPOSE 5000
